Create main struture of website
Compotes/compotes.github.io pull request #1
Opened 2016-09-16 17:11 UTC by gkaretka

Signed-off-by: Gregor Karetka <karetka.gregor@gmail.com>

2016-09-16 17:17 UTC, pepol requested changes
Please remove the non-minified versions of bootstrap files.

2016-09-16 17:23 UTC, pepol commented on bootstrap-3.3.7/js/npm.js
> +// This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.
Is this file required? If not, please delete it.

2016-09-16 17:24 UTC, pepol commented on css/main.css
> +}
This line is missing a newline character at the end. Please add it.

2016-09-16 17:25 UTC, pepol commented on index.html
> +        <script src="js/jquery-3.1.0.min.js"></script>
Wouldn't it work better to just use the absolute addressing: `/js/jquery/...` ?

Also, if it's possible, please delete bootstrap and jquery directories and move the appropriate files into either `js/` or `css/` directories as necessary. Thanks.

2016-09-16 17:26 UTC, pepol commented on sk/about.html
> +</html>
Same comments as for `index.html`.

2016-09-16 17:27 UTC, pepol commented on en/index.html
> +</html>
Same comments as for `index.html`.

2016-09-16 17:27 UTC, pepol commented on en/about.html
> +</html>
Same comments as for `index.html`.

2016-09-16 17:28 UTC, pepol requested changes
@gkaretka please change all the links to use the absolute format, if that is possible (please test it and if it's not possible, let me know).

2016-09-16 17:44 UTC, gkaretka commented on bootstrap-3.3.7/js/npm.js
> +// This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.
no

2016-09-16 17:49 UTC, gkaretka commented
done

2016-09-16 21:52 UTC, pepol requested changes
@gkaretka it seems like you (hopefully mistakenly) marked all files as executable (`755` chmod). Please return them to `644` and keep only directories as `755`.

2016-09-17 07:12 UTC, gkaretka commented
done

2016-09-17 13:11 UTC, pepol approved these changes

2016-09-17 13:11 UTC, pepol commented
@gkaretka Ship it!

2016-09-17 13:11 UTC, merged